FROM rust:1.97-slim-trixie

ARG USERNAME=vscode 
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    bash \
    binutils \
    ca-certificates \
    clang \
    cpio \
    curl \
    erofs-utils \
    git \
    kmod \
    less \
    libclang-dev \
    linux-image-amd64 \
    make \
    mtools \
    ovmf \
    parted \
    qemu-system-arm \
    qemu-system-x86 \
    ssh \
    sudo \
    systemd-boot-efi \
    vim \
    xz-utils

RUN rustup component add clippy rustfmt \
    && cargo install cargo-edit --locked



# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER ${USERNAME}

# Setup antigravity
RUN curl -fsSL https://antigravity.google/cli/install.sh | bash
RUN bash && echo 'export PATH="/home/user/.local/bin:$PATH"' >> ~/.bashrc